### ISSUE TITLE
incorrect doc comments in the net library

### ISSUE THREAD

**Issue by zoombahh** [INPStarfall/Starfall#218]
in Starfall / lua / starfall / libs_sh / net.lua the parameter names dont match the names in the doc blocks above the functions.

**code:**

``` lua
-- @param integer The integer to be written
-- @param bitCount The amount of bits the integer consists of

function net_library.writeInt( t, n )
```

**and documentation:**

```
net_library.writeInt (t, n, integer, bitCount)
    Writes an integer to the net message
    Parameters:

        t:
        n:
        integer: The integer to be written
        bitCount: The amount of bits the integer consists of
```
